### ISSUE TITLE
Error: Cannot find module 'tailwindcss/jit/pluginUtils'

### ISSUE THREAD

**Issue by RohitM-IN** [shimyshack/tailwindcss-pseudo-element-plugin#2]
I installed the npm lib and after adding it to plugins i am getting :

i am running `"tailwindcss": "^2.2.16"`  and using `"laravel-mix": "^6.0.31"`

```
ERROR in ./css/theme.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module 'tailwindcss/jit/pluginUtils'
Require stack:
- D:\dev\html\manga tailwind\node_modules\@shimyshack\tailwindcss-pseudo-element-plugin\src\index.js
- D:\dev\html\manga tailwind\tailwind.config.js
- D:\dev\html\manga tailwind\node_modules\tailwindcss\lib\index.js
- D:\dev\html\manga tailwind\webpack.mix.js
- D:\dev\html\manga tailwind\node_modules\laravel-mix\setup\webpack.config.js
- D:\dev\html\manga tailwind\node_modules\webpack-cli\lib\webpack-cli.js
- D:\dev\html\manga tailwind\node_modules\webpack-cli\lib\bootstrap.js
- D:\dev\html\manga tailwind\node_modules\webpack-cli\bin\cli.js
- D:\dev\html\manga tailwind\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (D:\dev\html\manga tailwind\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\dev\html\manga tailwind\node_modules\@shimyshack\tailwindcss-pseudo-element-plugin\src\index.js:2:32)
    at Module._compile (D:\dev\html\manga tailwind\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at processResult (D:\dev\html\manga tailwind\node_modules\webpack\lib\NormalModule.js:721:19)
    at D:\dev\html\manga tailwind\node_modules\webpack\lib\NormalModule.js:827:5
    at D:\dev\html\manga tailwind\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\dev\html\manga tailwind\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\dev\html\manga tailwind\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (D:\dev\html\manga tailwind\node_modules\postcss-loader\dist\index.js:142:7
```
tailwind config looks like : 

```
module.exports = {
  mode: 'jit',  // some time i comment this line but its not working even with this mode on
  purge: {
    content: [
      './build/**/*.html',
      './build/**/*.js',

    ],
  },
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/line-clamp'),
    require('@shimyshack/tailwindcss-pseudo-element-plugin'),
  ],
}

```

my webpack.mix.js

```
const mix = require('laravel-mix');

mix.postCss('css/theme.css', 'build/css', [
    require('tailwindcss'),
    require('autoprefixer'),
])
```

am i missing anything in install ??

**Comment by jshimkoski** [comment]
I’ll take a look at this tomorrow. Sorry for the inconvenience.

**Comment by dario-baumberger** [comment]
maybe this helps:

const { asValue, nameClass } = require('@tailwindcss/jit/src/pluginUtils');

As a quick fix, you can copy and paste the content (plugin(...)) from src/index.js into your tailwind.config.js


But still have problems
